use TMPKM_UNIVER;
go

--Subject 8
--Доказательство коммутативности
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME from  TEACHER FULL OUTER JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT;
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME from  PULPIT FULL OUTER JOIN TEACHER on TEACHER.PULPIT = PULPIT.PULPIT;


--left outer join + right outer join = full outer join 
select TEACHER.SECOND_NAME,
		PULPIT.PULPIT_NAME 
from TEACHER LEFT OUTER JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT  
UNION 
select TEACHER.SECOND_NAME,
		PULPIT.PULPIT_NAME
from TEACHER RIGHT OUTER JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT

--inner join == full outer join
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME
from TEACHER FULL outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT where TEACHER.SECOND_NAME  IS NOT NULL

select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME
from TEACHER inner JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT

--Содержит данные левой и не содержит правой
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME
from TEACHER FULL outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT where PULPIT.PULPIT IS NULL

--Содержит данные правой и не содержит левой
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME
from TEACHER FULL outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT where TEACHER.SECOND_NAME  IS NULL

--И правой, и левой
select TEACHER.SECOND_NAME, PULPIT.PULPIT_NAME
from TEACHER FULL outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT where TEACHER.SECOND_NAME  IS NOT NULL

--Subject 9
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPE from AUDITORIUM CROSS JOIN AUDITORIUM_TYPE where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
