use TMPKM_UNIVER;
go

--Subject 6
select ISNULL (TEACHER.SECOND_NAME, '***')[TEACHER],PULPIT.PULPIT_NAME
from PULPIT LEFT outer JOIN TEACHER on TEACHER.PULPIT = PULPIT.PULPIT;
--Reverce PULPIT and TEACHER

--Subject 7
select ISNULL (TEACHER.SECOND_NAME, '***')[TEACHER],PULPIT.PULPIT_NAME
from TEACHER LEFT outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT;
--Use RIGHT OUTER JOIN 
select ISNULL (TEACHER.SECOND_NAME, '***')[TEACHER],PULPIT.PULPIT_NAME
from TEACHER RIGHT outer JOIN PULPIT on TEACHER.PULPIT = PULPIT.PULPIT;